name: Build and deploy zhwiki

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Dict version"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android environment
        uses: android-actions/setup-android@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache stack
        id: cache-stack
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global

      - name: Checkout scripts
        uses: actions/checkout@v3

      - name: Checkout plugin-scaffold
        uses: actions/checkout@v3
        with:
          path: plugin-scaffold
          repository: fcitx5-android/plugin-scaffold
    
      - name: Build Release APK
        env:
          ZHWIKI_DICT_VER: "${{ inputs.version }}"
          ZHWIKI_CONVERTER_VER: "0.2.4"
        working-directory: plugin-scaffold
        run: scripts/build-zhwiki.sh

      - name: Sign APK
        env:
          SIGN_KEY_BASE64: "${{ secrets.SIGN_KEY_BASE64 }}"
          SIGN_KEY_ALIAS: "${{ secrets.SIGN_KEY_ALIAS }}"
          SIGN_KEY_PWD: "${{ secrets.SIGN_KEY_PWD }}"
        working-directory: plugin-scaffold
        run: ${GITHUB_WORKSPACE}/scripts/sign-apk.sh ./out/app/build/outputs/apk/release/*.apk
