name: Build and deploy moegirl

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Dict version"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android environment
        uses: android-actions/setup-android@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache stack
        id: cache-stack
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global

      - name: Checkout scripts
        uses: actions/checkout@v3

      - name: Checkout plugin-scaffold
        uses: actions/checkout@v3
        with:
          path: plugin-scaffold
          repository: fcitx5-android/plugin-scaffold
    
      - name: Build Release APK
        env:
          MOEGIRL_VER: ${{ inputs.version }}
        working-directory: plugin-scaffold
        run: ${GITHUB_WORKSPACE}/scripts/build-moegirl.sh

      - name: Sign APK
        id: sign
        env:
          SIGN_KEY_BASE64: "${{ secrets.SIGN_KEY_BASE64 }}"
          SIGN_KEY_ALIAS: "${{ secrets.SIGN_KEY_ALIAS }}"
          SIGN_KEY_PWD: "${{ secrets.SIGN_KEY_PWD }}"
        working-directory: plugin-scaffold
        run: ${GITHUB_WORKSPACE}/scripts/sign-apk.sh ./out/*.apk
      - name: Deploy
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: "${{ steps.sign.outputs.signed_path }}"
          remote_path: "${{ steps.sign.outputs.remote_path }}"
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
