name: Build and deploy zhwiki

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Dict version"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android environment
        uses: android-actions/setup-android@v2

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install ghc libghc-mustache-dev libghc-shake-dev
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: fcitx5-android/plugin-scaffold
      
      - name: Build
        env:
          VERSION: ${{ inputs.version }}
        run: |
          cat << EOF > build.cfg
          project_name = fcitx5-android-plugin-pinyin-zhwiki
          package_name = org.fcitx.fcitx5.android.plugin.pinyin_zhwiki
          aboutlibraries_version = 10.7.0
          main_version = 49f75dd319
          desugarJDKLibs_version = 2.0.3
          kotlin_version = 1.8.20
          android_version = 8.0.1
          build_version_name = $_ver
          version_code = $_ver
          build_commit_hash = unknown
          app_name_debug = Fcitx5 for Android (zhwiki dict | Debug)
          app_name_release = Fcitx5 for Android (zhwiki dict)
          plugin_description = Fcitx 5 Pinyin Dictionary from zh.wikipedia.org
          plugin_api_version = 0.1
          EOF
          runghc Main.hs
          mkdir -p out/app/src/main/assets/usr/share/fcitx5/pinyin/dictionaries/
          curl -vL https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/$_converterver/zhwiki-$_ver.dict -o out/app/src/main/assets/usr/share/fcitx5/pinyin/dictionaries/zhwiki-$_ver.dict
          cd out
          ./gradlew assembleRelease
