name: Check zhwiki Update
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * *"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - id: fdroid
        name: Get version from fdroid
        run: |
          X=$(curl -s https://f5a.torus.icu/fdroid/repo/index-v1.json | jq -r '.packages."org.fcitx.fcitx5.android.plugin.pinyin_zhwiki"[0].versionCode')
          echo "version=$X" >> $GITHUB_OUTPUT
      - id: archlinux
        name: Get version from archlinux [extra]
        run: |
          X=$(curl -s https://archlinux.org/packages/extra/any/fcitx5-pinyin-zhwiki/json/ | jq -r '.pkgver')
          [[ $X =~ \.[0-9]*$ ]] && echo "converter=${X//$BASH_REMATCH/}" >> $GITHUB_OUTPUT
          [[ $X =~ [0-9]*$ ]] && echo "version=$BASH_REMATCH" >> $GITHUB_OUTPUT
      - name: Check if needs update
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          CONVERTER="${{ steps.fdroid.outputs.converter }}"
          FDROID="${{ steps.fdroid.outputs.version }}"
          ARCHLINUX="${{ steps.archlinux.outputs.version }}"
          echo "FDROID=$FDROID; ARCHLINUX=$ARCHLINUX"
          if [ "$FDROID" != "$ARCHLINUX" ]; then
            echo "fdroid and archlinux version not match"
            gh workflow run build-zhwiki.yml -f converter=$CONVERTER -f version=$ARCHLINUX --repo ${{ github.repository }}
          else
            echo "skip build" 
          fi
