name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke run
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
           gh workflow run run.yml -f target=deploy --repo ${{ github.repository }}
